blogProject/models.py
from werkzeug.security import generate_password_hash, check_password_hash

from . import db
from datetime import datetime
from flask_login import UserMixin


class Admin(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(80), nullable=False)  # Removed unique=True
    is_active = db.Column(db.Boolean, default=True)


    # hashes passwords
    def set_password(self, password):
        self.password = generate_password_hash(password)

    # checks password that has been hashed
    def check_password(self, password):
        return check_password_hash(self.password, password)

    # Define the relationship
    posts = db.relationship('BlogPost', backref='admin', lazy='dynamic')

    def get_id(self):
        return self.id


class BlogPost(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), unique=True, nullable=False)
    content = db.Column(db.Text, nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    admin_id = db.Column(db.Integer, db.ForeignKey('admin.id'), nullable=False)

blogProject/forms.py
# src/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

blogProject/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config
from flask_login import LoginManager
import logging

db = SQLAlchemy()
login_manager = LoginManager()

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    Migrate(app, db)
    login_manager.init_app(app)

    with app.app_context():
        from blogProject.models import BlogPost, Admin
        from blogProject.routes import main as main_blueprint
        login_manager.login_view = 'login'
        app.register_blueprint(main_blueprint)

        @app.route('/')
        @app.route('/blog')
        def view_blog():
            # put application's code here
            return render_template('view_blog_post.html', values=BlogPost.query.all())
    return app


@login_manager.user_loader
def load_user(user_id):
    from blogProject.models import Admin
    return Admin.query.get(int(user_id))

blogProject/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, logout_user

from blogProject.forms import LoginForm
from blogProject.models import BlogPost


from .services import create_admin, user_login_manager, upload_blog_posts, save_blog_post_edit, remove_blog_post
# Create a Blueprint named 'main'
main = Blueprint('main', __name__)


@main.route('/signup', methods=['GET', 'POST'])
def signup_admin():
    if request.method == 'POST':
        create_admin(request.form.get("full_name"), request.form.get("admin_email"), request.form.get("admin_password"))
    return render_template('create_admin_user.html')


@main.route('/login', methods=['GET', 'POST'])
def login_admin():
    form = LoginForm()
    if current_user.is_authenticated:
        return render_template('create_blog_post.html')

    if request.method == 'POST' and form.validate_on_submit():
        if user_login_manager(form):
            return render_template('create_blog_post.html')
        else:
            flash('Invalid email or password', 'error')
            return render_template('login_admin_user.html', form=form)
    return render_template('login_admin_user.html', form=form)


@main.route('/create_blog', methods=['GET'])
def create_blog_post():
    if current_user.is_authenticated:
        return render_template('create_blog_post.html')
    return render_template('view_blog_post.html')


@main.route('/edit_blog_post', methods=['GET'])
def edit_blog_post():
    if current_user.is_authenticated:
        post = BlogPost.query.filter_by(admin_id=current_user.id).all()
        return render_template('edit_blog_post.html',values=post)
    return render_template('view_blog_post.html')


@main.route('/delete_blog_post', methods=['GET'])
def delete_blog_post():
    if current_user.is_authenticated:
        post = BlogPost.query.filter_by(admin_id=current_user.id).all()
        return render_template('delete_blog_post.html', values = post)
    return render_template('view_blog_post.html')



## uploads the blog
@main.route('/upload_blog', methods=['POST'])
def upload_blog_post():
    upload_blog_posts(request.form.get("blog_title"), request.form.get("blog_content"))## admin_id yet to be done
    return render_template('create_blog_post.html')


## save changes to the blog
@main.route('/save_changes', methods=['POST'])
def save_changes():
    save_blog_post_edit(request.form.get("blog_title"),request.form.get("blog_content"),request.form.get("blog_id"))
    post = BlogPost.query.filter_by(admin_id=current_user.id).all()
    return render_template('edit_blog_post.html', values=post)


@main.route('/remove_blog', methods=['POST'])
def remove_blog():
    post = BlogPost.query.filter_by(admin_id=current_user.id).all()
    remove_blog_post(request.form.get("blog_id"))
    return 'Blog post deleted', 200


@main.route('/logout', methods=['POST'])
def logout_admin():
    logout_user()
    return redirect(url_for('main.login_admin'))

blogProject/templates/Delete_blog_post.html
{%extends 'base_template_for_admin.html'%}
 {%block title%}
Delete Blog Post
 {% endblock %}

{% block content %}
<div class="w3-top">
  <div class="w3-row w3-padding w3-black">
    <div class="w3-col s3">

            <a href="/create_blog"><button class="w3-button w3-block w3-black" >Create Blog Post</button></a>
</div>
    <div class="w3-col s3">

            <a href="/edit_blog_post"><button class="w3-button w3-block w3-black" >Edit Blog Post</button></a>
     </div>
    <div class="w3-col s3">
      <a href="#" class="w3-button w3-block w3-black">Delete Blog Post</a>
    </div>
    <div class="w3-col s3">
     <form action="/logout" method="POST">

   <button class="w3-button w3-block w3-black" type="submit" >Logout</button>

        </form>
    </div>
  </div>
</div>

<!-- Contact/Area Container -->
<div class="w3-container" id="where" style="padding-bottom:32px;">
  <div class="w3-content" style="max-width:700px">
    <h5 class="w3-center w3-padding-48"><span class="w3-tag w3-wide">Delete Blog Post</span></h5>


        {% if values != None %}
        {% for x in values %}
            <form method="POST">
      <p class="w3-input w3-padding-16 w3-border" id="blog-{{ x.id }}"> {{ x.title }}</p>
      <button class="w3-button w3-black delete_post" type="submit" data-blog_id="{{ x.id }}" data-blog_post="#blog-{{ x.id }}">Delete Blog Post</button>
            </form>
        {% endfor %}

  {% else %}
      <h1 class="w3-input w3-padding-16 w3-border">There is no stored blog post</h1>
  {% endif %}


  </div>
</div>

    <script>
    $('.delete_post').on('click', function(e){
        e.preventDefault()
        let button = $(this)
        let blog_id = button.data('blog_id')
        let blog_post_id = button.data('blog_post')
        let blog_post = $(blog_post_id)
        const delete_url = `{{ url_for('main.remove_blog') }}`
        $.ajax({
            type: 'POST',
            url: delete_url,
            data: {"blog_id": blog_id},
            success: function (response) {
                blog_post.hide();
                button.hide()
            },
            error: function (e) {
                alert(`An error occurred  ${e}`)
            }
        })
    })


    </script>

 {% endblock %}

blogProject/templates/base_template_for_admin.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='admin_template_stylesheet.css')}}">
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>


    {% block title %}
    <title>Title</title>
    {% endblock %}

</head>
<body>
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}" style="margin-top: 35px">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}
{%  block content %}

{% endblock %}

<script>
// Tabbed Menu
function openMenu(evt, menuName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("menu");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(menuName).style.display = "block";
  evt.currentTarget.firstElementChild.className += " w3-dark-grey";
}

</script>
</body>
</html>

blogProject/templates/create_admin_user.html
{% extends 'base_template_for_admin.html' %}
{% block title %}
Sign Up
{% endblock %}

{% block content %}
<!-- Navbar (sit on top) -->
        <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='create_and_login_template.css')}}">
<div class="w3-top">
  <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
    <a href="#home" class="w3-bar-item w3-button">My Blog Post</a>
    <!-- Right-sided navbar links. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
     <a href="blog" class="w3-bar-item w3-button">View Blog Post</a>
      <a href="login" class="w3-bar-item w3-button">Login</a>
    </div>
  </div>
</div>

  <!-- Contact Section -->
  <div class="w3-container w3-padding-64" id="contact">
    <h1>Sign Up</h1><br>
    <form action="/signup" method="POST">
      <p><input class="w3-input w3-padding-16" type="text" placeholder="Full_Name" name="full_name"></p>
      <p><input class="w3-input w3-padding-16" type="email" placeholder="Email address" name="admin_email"></p>
      <p><input class="w3-input w3-padding-16" type="Password" placeholder="Password" name="admin_password" ></p>
      <p><button class="w3-button w3-light-grey w3-section" type="submit">Sign Up</button></p>
    </form>
  </div>

<!-- End page content -->
</div>
{% endblock %}

blogProject/templates/create_blog_post.html
{%extends 'base_template_for_admin.html'%}
 {%block title%}
Create Blog Post
 {% endblock %}

{% block content %}
<!-- Links (sit on top) -->
<div class="w3-top">
  <div class="w3-row w3-padding w3-black">
    <div class="w3-col s3">
      <a href="#" class="w3-button w3-block w3-black">Create Blog Post</a>
    </div>
    <div class="w3-col s3">
            <a href="/edit_blog_post"> <button class="w3-button w3-block w3-black" >Edit Blog Post</button></a>
  </div>
    <div class="w3-col s3">
            <a href="/delete_blog_post"><button class="w3-button w3-block w3-black">Delete Blog Post</button></a>
    </div>
    <div class="w3-col s3">
        <form action="/logout" method="POST">
            <button class="w3-button w3-block w3-black" type="submit" >Logout</button>
        </form>
    </div>
  </div>
</div>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='create_and_login_template.css')}}">
<!-- Contact/Area Container -->
<div class="w3-container" id="where" style="padding-bottom:32px;">
  <div class="w3-content" style="max-width:700px">
    <h5 class="w3-center w3-padding-48"><span class="w3-tag w3-wide">Create a Blog Post</span></h5>
    <form action="/upload_blog" method="POST">
      <input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Blog Title" name="blog_title" required>
        <br>
      <textarea class="w3-input w3-padding-16 w3-border" type="text"  name="blog_content" required></textarea>
        <br>
      <button class="w3-button w3-black" type="submit">Create</button>
    </form>
  </div>
</div>


{% endblock %}

blogProject/templates/edit_blog_post.html
{%extends 'base_template_for_admin.html'%}

 {%block title%}
Edit Blog Post
 {% endblock %}

{% block content %}

<!-- Links (sit on top) -->
<div class="w3-top">
  <div class="w3-row w3-padding w3-black">
    <div class="w3-col s3">

            <a href="/create_blog"><button class="w3-button w3-block w3-black" >Create Blog Post</button></a>
      </div>
    <div class="w3-col s3">
      <a href="#about" class="w3-button w3-block w3-black">Edit Blog Post</a>
    </div>
    <div class="w3-col s3">

            <a href="/delete_blog_post"><button class="w3-button w3-block w3-black"  >Delete Blog Post</button></a>

 </div>
    <div class="w3-col s3">
     <form action="/logout" method="POST">

   <button class="w3-button w3-block w3-black" type="submit" >Logout</button>

        </form> </div>
  </div>
</div>

<!-- Contact/Area Container -->
<div class="w3-container" id="where" style="padding-bottom:32px;">
  <div class="w3-content" style="max-width:700px">
    <h5 class="w3-center w3-padding-48"><span class="w3-tag w3-wide">Edit Blog Post</span></h5>

        {% if values != None %}

      {% for x in values %}
          <form action="/save_changes" method="POST">
      <p><input class="w3-input w3-padding-16 w3-border" type="text" name="blog_title" value="{{ x.title }}"></p>
      <textarea class="w3-input w3-padding-16 w3-border" type="text" name="blog_content" >{{ x.content }}</textarea>
        <input type="hidden" name="blog_id" value="{{ x.id }}">
      <p><button class="w3-button w3-black" type="submit">Save Changes</button></p>
          </form>
        {% endfor %}
  {% endif %}
  {% if values == None %}
      <h1 class="w3-input w3-padding-16 w3-border">There is no stored blog post</h1>
  {% endif %}

  </div>
</div>

 {% endblock %}

blogProject/templates/login_admin_user.html
{% extends 'base_template_for_admin.html' %}
{% block title %}
    Login
    {% endblock %}

{% block content %}

<div class="w3-top">
  <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
    <a href="#home" class="w3-bar-item w3-button">My Blog Post</a>
    <!-- Right-sided navbar links. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="blog" class="w3-bar-item w3-button">View Blog Post</a>
      <a href="signup" class="w3-bar-item w3-button">Sign up</a>
    </div>
  </div>
</div>

  <!-- Contact Section -->
  <div class="w3-container w3-padding-64" id="contact">
    <h1>Login</h1><br>
      <!--
    <form action="/login" method="POST">
      <p><input class="w3-input w3-padding-16" type="email" placeholder="Email address" name="admin_email"></p>
      <p><input class="w3-input w3-padding-16" type="Password" placeholder="Password" name="admin_password"></p>
      <p><button class="w3-button w3-light-grey w3-section" type="submit">Login</button></p>
    </form>
    -->

 <form action="/login" method="POST">
    {{ form.hidden_tag() }}
    <p>
        {{ form.email(size=32, class_='w3-input w3-padding-16', placeholder="Email") }}
    </p>
    <p>
        {{ form.password(size=32, class_='w3-input w3-padding-16' , placeholder="password") }}
    </p>
    <p>
        {{ form.submit(class_='w3-button w3-light-grey w3-section' ) }}
    </p>
</form>
  </div>

<!-- End page content -->
</div>
{% endblock %}

blogProject/templates/view_blog_post.html
{% extends 'base_template_for_admin.html' %}
{% block title %}
    View Blog Post
{% endblock %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='create_and_login_template.css')}}">

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
    <a  class="w3-bar-item w3-button">My Blog Post</a>
    <!-- Right-sided navbar links. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="signup" class="w3-bar-item w3-button">Sign up</a>
      <a href="login" class="w3-bar-item w3-button">Login</a>
    </div>
  </div>
</div>

<!-- Header -->
    {% if values != None %}

    {% for x in values%}
<!-- Page content -->
<div class="w3-content" style="max-width:1100px">


    <div class="w3-center m6 w3-padding-large">

        <h1 class="w3-large">{{ x.title }} </h1>
        <br>
        <br>
      <p>{{ x.content }} </p>

      </div>
  </div>
        {% endfor %}
{% endif %}
{% if values == None %}
    <div class="w3-center m6 w3-padding-large">
      <h1 class="w3-center">No Blog Post avaliable</h1><br> </div>
  <hr>
{% endif %}
{% endblock %}